version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Nginx draait op poort 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www/html
    depends_on:
      - laravel
      - react
    networks:
      - app-network

  laravel:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    ports:
      - "8000:8000"  # Laravel draait op poort 8000 voor de API
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME:-laravel_db}
      DB_USERNAME: ${DB_USER:-laravel_user}
      DB_PASSWORD: ${DB_PASS:-password}
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  react:
    build:
      context: ./react_app
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"  # React draait op poort 3000
    volumes:
      - ./react_app:/app
    command: ["npm", "start"]  # Voor ontwikkelserver
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DB:-laravel_db}
      MYSQL_USER: ${MYSQL_USER:-laravel_user}
      MYSQL_PASSWORD: ${MYSQL_PASS:-password}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
